version: "rip"

services:
  nginx:
    init: true
    container_name: nginx
    image: nginx_img
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

  mariadb:
    init: true
    container_name: mariadb
    image: mariadb_img
    env_file:
      - .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress_img
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - WP_URL=${WP_URL}
        - WP_ADMIN_USER=${WP_ADMIN_USER}
        - WP_ADMIN_PASS=${WP_ADMIN_PASS}
        - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
        - WP_USER=${WP_USER}
        - WP_PASS=${WP_PASS}
        - WP_MAIL=${WP_MAIL}
        - WP_TITLE=${WP_TITLE}
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tamather/data/db
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tamather/data/wp

networks:
  inception:
    driver: bridge
